name: Ruff Lint Check

on:
  push:
    branches: [ "main" ]  # Запускать при пуше в main
  pull_request:           # И при создании/обновлении PR
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Клонирует репозиторий

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"  # Укажите вашу версию Python

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check .  # Проверяет все файлы в проекте
